core/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls.conf import include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.index, name='index'),

    path('funcionarios/', include(('funcionarios.urls', 'funcionarios'),namespace='funcionarios')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace= 'clientes')),
    path('contas/', include(('accounts.urls', 'accounts'), namespace= 'accounts')),
]

funcionarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registro/', views.funcionario_cadastro, name='funcionario_cadastro'),
    path('lista/', views.funionarios_lista, name='funcionario_lista'),
    
    path('agendas/', views.agenda_lista, name="agenda_lista"),
    path('agendar/', views.agenda_cadastro, name='agenda_cadastro'),
    path('agendar/atualizar/<int:pk>/', views.agenda_atualizar, name='agendar_consulta_atualizar'),
    path('agendar/apagar/<int:pk>/', views.agenda_deletar, name='agendar_consulta_deletar'),
    
    path('medico/lista/', views.medico_lista, name="medico_lista"),
    path('funcionarios/medico/cadastro', views.medico_cadastro, name='medico_cadastro'),
    path('medico/especialidade/cadastro/', views.especialidade_cadastro, name='especialidade_cadastro'),
    path('medico/especialidade/lista/', views.especialidade_lista, name="especialidade_lista"),
]

funcionarios/models.py
import holidays
from datetime import date
from django.db import models
from django.conf import settings
from django_cpf_cnpj.fields import CPFField
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.db.models.fields.related import OneToOneField, ForeignKey

class Funcionario(models.Model):
    
    nome = models.CharField(verbose_name='Nome', max_length=30)
    sobrenome = models.CharField(verbose_name='Sobremone', max_length=200)
    
    cpf = CPFField(verbose_name="CPF", max_length=50, unique=True, masked=True)
    GENERO = (
        ("MAS", "Masculino"),
        ("FEM", "Feminino"),
        ("OTR", "Outro"),
    )
    
    genero = models.CharField(verbose_name="Genero", max_length=9, choices=GENERO)
    
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="O número precisa estar neste formato: \
                        '+99 99 9999-0000'."
    )
    telefone = models.CharField(verbose_name="Telefone", validators=[phone_regex],max_length=17, null=True, blank=True)
    
    cep = models.CharField('CEP', max_length=9)
    rua = models.CharField('Rua', max_length=200)
    numero = models.CharField('Numero', max_length=15)
    complemento = models.CharField('Complemento', max_length=200, blank=True)
    municipio = models.CharField('Municipio', max_length=20)
    unidade_federal = models.CharField('Unidade Federal', max_length=2)
    
    data_nacimento = models.DateField('Data de Nacimento')
    data_contratacao = models.DateField('Data de contratação')
    is_medico = models.BooleanField('É medico', default=False)
    is_ativo = models.BooleanField('Está ativo', default=True)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        verbose_name='Usuário', 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.cpf}'
    

class Especialidade(models.Model):
    especialidade = models.CharField('Especialidades', max_length=200, unique=True)
    descricao = models.CharField('Descrição', max_length=1000)

    def __str__(self):
        return f'{self.especialidade}'

class Medico(models.Model):
    nome = models.CharField('Nome', max_length=200)
    crm = models.CharField('CRM', max_length=13,unique=True , validators=[
        RegexValidator(
            regex=r'^\d{7}-\d{2}$',
            message="O CRM precisa estar no seguinte formato: \
                                'xxxxxxx-UF'",
            code='Invalid_crm')
    ])
    funcionario = OneToOneField(Funcionario, on_delete=models.CASCADE, related_name='funcioanrios')
    especialidade = ForeignKey(Especialidade, on_delete=models.CASCADE, related_name='especialidades' )

    def __str__(self):
        return f'{self.nome}'
    
def is_feriado(dia):
    objeto_feriados = holidays.country_holidays('BR')
    ano = f'{date.today()}'

    for objeto_feriado in objeto_feriados[f'{ano[:5]}-01-01' : f'{ano[:5]}-12-31']:

        if dia == objeto_feriado:
            return True

def valida_dia(value):
    hoje = date.today()
    dia_semana = date.fromisoformat(f'{value}').weekday()

    if value < hoje:
        raise ValidationError('Não é possivel escolher uma data atrasada.')
    
    elif is_feriado(value) or dia_semana == 6:
        raise ValidationError('Escolha um dia util')

# to do: gerador de horarios

# def gera_horarios(dia):
#     horarios = []
    
#     if not is_feriado(dia):
#         horarios = [(f'{i}', f'{i + 8}:{j}0' if i+8 > 9 else f'0{i + 8}:00') for i in range(1, 11) for j in range(0,4,3)]
        
#         return horarios
#     else:
#         horarios = [(f'{i}', f'{i + 8}:00' if i+8 > 9 else f'0{i + 8}:00') for i in range(1, 5)]
#         return horarios


class Servico(models.Model):
    servico = models.CharField('Serviço', max_length=200)
    descricao = models.CharField('Descrição', max_length=1000)
    valor = models.FloatField('Valor')



class Agenda(models.Model):
    
    medico = ForeignKey(Medico, on_delete=models.CASCADE, related_name='Agenda')
    dia = models.DateField(help_text='Ensira uma data', validators=[valida_dia])

    HORARIOS = (
        ('1', '09:00'),
        ('2', '09:30'),
        ('3', '10:00'),
        ('4', '10:30'),
        ('5', '11:00'),
        ('6', '11:30'),
        ('7', '12:00'),
        ('8', '12:30'),
        ('9', '13:00'),
        ('10', '13:30'),
        ('11', '14:00'),
        ('12', '14:30'),
        ('13', '15:00'),
        ('14', '15:30'),
        ('15', '16:00'),
        ('16', '16:30'),
        ('17', '17:30'),
        ('18', '17:30'),
        ('19', '18:00'),
    )
    
    horario = models.CharField(max_length=10, choices=HORARIOS)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        verbose_name='Usuário', 
        on_delete=models.CASCADE
    )
    
    servico = ForeignKey(Servico, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('horario', 'dia')
        
    def __str__(self):
        return f'{self.dia.strftime("%b %d %Y")} - {self.get_horario_display()} - {self.medico}'

funcionarios/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Funcionario,Medico, Agenda, Especialidade
from .froms import *


class TestMixinIsAdmin(UserPassesTestMixin):
    def test_func(self):
        is_admin_or_is_staff = self.request.user.is_superuser or \
            self.request.user.is_staff
        return bool(is_admin_or_is_staff)

    def handle_no_permission(self):
        messages.error(
            self.request, "Você não tem permissões!"
        )
        return redirect("accounts:index")
    

class FuncionarioCreateView(LoginRequiredMixin, TestMixinIsAdmin, CreateView):
    model = Funcionario
    login_url = 'accounts:login'
    template_name = 'funcionarios/cadastro.html'
    # form_class = FuncionarioCreateForm
    fields =  ['nome', 'sobrenome','cpf', 'genero', 'telefone', 'cep', 'rua', 'numero', 'complemento', 'municipio', 'unidade_federal', 'data_nacimento', 'data_contratacao', 'is_medico']

    
    if Funcionario.is_medico == 1:
        success_url = reverse_lazy('funcionarios:medico_cadastro') 
    else:
        success_url = reverse_lazy('funcionarios:funcionarios_lista')

class FuncionarioListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'funcionarios/funcionario_lista.html'

    def get_queryset(self):
        return Medico.objects.all().order_by('-pk')
    

class MedicoCreateView(LoginRequiredMixin, TestMixinIsAdmin, CreateView):

    model = Medico
    login_url = 'accounts:login'
    template_name = 'funcionarios/cadastro.html'
    # form_class = MedicoCreateForm
    fields = ['crm', 'funcionario', 'especialidade']
    success_url = reverse_lazy('funcionarios:medicos_lista')
    
class MedicoListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'funcionarios/medico_lista.html'

    def get_queryset(self):
        return Medico.objects.all().order_by('-pk')
    
class EspecialidadeCreateView(LoginRequiredMixin, TestMixinIsAdmin, CreateView):

    model = Especialidade
    login_url = 'accounts:login'
    template_name = 'funcionarios/cadastro.html'
    fields = ['especialidade','descricao']
    success_url = reverse_lazy('funcionarios:especialidade_lista')
    
class EspecialidadeListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'funcionarios/especialidade_lista.html'

    def get_queryset(self):
        return Especialidade.objects.all().order_by('-pk')


class AgendaCreateView(LoginRequiredMixin, TestMixinIsAdmin, CreateView):

    model = Agenda
    login_url = 'accounts:login'
    template_name = 'funcionarios/agenda_cadastro.html'
    fields = ['medico', 'dia', 'horario']
    success_url = reverse_lazy('funcionarios:agenda_lista')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class AgendaUpdateView(LoginRequiredMixin, TestMixinIsAdmin, UpdateView):

    model = Agenda
    login_url = 'accounts:login'
    template_name = 'medicos/agenda_cadastro.html'
    fields = ['medico', 'dia', 'horario']
    success_url = reverse_lazy('funcionarios:agenda_lista')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class AgendaDeleteView(LoginRequiredMixin, TestMixinIsAdmin, DeleteView):
    model = Agenda
    success_url = reverse_lazy('medicos:agenda_lista')
    template_name = 'form_delete.html'

    def get_success_url(self):
        messages.success(self.request, "Consulta excluída com sucesso!")
        return reverse_lazy('medicos:agenda_lista')


class AgendaListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'funcionarios/agenda_lista.html'

    def get_queryset(self):
        return Agenda.objects.filter().order_by('-pk')



funcionario_cadastro = FuncionarioCreateView.as_view()
funionarios_lista = FuncionarioListView.as_view()

medico_cadastro = MedicoCreateView.as_view()
medico_lista = MedicoListView.as_view()

especialidade_cadastro = EspecialidadeCreateView.as_view()
especialidade_lista = EspecialidadeListView.as_view()

agenda_cadastro = AgendaCreateView.as_view()
agenda_atualizar = AgendaUpdateView.as_view()
agenda_lista = AgendaListView.as_view()
agenda_deletar = AgendaDeleteView.as_view()

templates/funcionarios/agenda_cadastro.html
{%extends 'base.html'%}

{% load widget_tweaks %}

{% block title %}
Cadastro de agendas
{% endblock %}

{% block conteudo %}

  <div class="row">
</div>
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h2>Agendar Consulta</h2>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.medico.errors %} has-error{% endif %}">
                  <label for="{{ form.medico.auto_id }}" class="col-md-3 control-label">
                  {{ form.medico.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.medico class="form-control" %}

                    {% for error in form.medico.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.dia.errors %} has-error{% endif %}">
                  <label for="{{ form.dia.auto_ud }}" class="col-md-3 control-label">
                  {{ form.dia.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.dia type="date" class="form-control" placeholder="01/01/2022" %}
                    {% for error in form.dia.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.horario.errors %} has-error{% endif %}">
                  <label for="{{ form.horario.auto_id }}" class="col-md-3 control-label">
                  {{ form.horario.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.horario class="form-control" %}

                    {% for error in form.horario.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-success">Salvar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

templates/funcionarios/agenda_lista.html
{%extends 'base.html'%}

{% load widget_tweaks %}

{% block title %}
Lista de Agendas
{% endblock %}

{% block conteudo %}

    <div class="d-flex justify-content-between p-2">
        <h2>Agendas Disponiveis</h2>
        <a class="btn btn-outline-secondary" href="{% url 'funcionarios:agenda_cadastro'%}">Criar nova agenda</a></span>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Medico</th>
                <th>Dia</th>
                <th>Horario</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            {% for consulta in object_list %}
            <tr>
                <td><a href=""># {{ consulta.pk }}</a></td>
                <td>{{ consulta.medico }}</td>
                <td>{{ consulta.dia|date:"d/m/Y" }}</td>
                <td>{{ consulta.get_horario_display }}</td>
                <td>
                    <a href="{% url 'medicos:agendar_consulta_atualizar' consulta.id %}" class="text-primary" style="padding-left: 10px; text-decoration: none;">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a href="{% url 'medicos:agendar_consulta_deletar' consulta.id %}" class="mr-1 text-danger" style="padding-left: 10px; text-decoration: none;">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/funcionarios/cadastro.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Cadastro | {{ block.super }}
{% endblock %}

{% block conteudo %}

  <div class="row">
      <div>
          <div class="page-header">
              <h2>Cadastro</h2>
          </div>
          <div>
            <a href="{% url 'index' %}">Inicio</a>
          </div>
          <form class="form-horizontal" method="post">
              {% csrf_token %}
              {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                  {{ error }}
              </div>
              {% endfor %}
              <fieldset>
                  {% for field in form %}
                  <div class="form-group{% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.auto_id }}" class="col-md-3 control-label">
                    {{ field.label }}</label>
                    <div class="col-md-9">
                      {% render_field field class="form-control" %}
                      {% for error in field.errors %}
                      <span class="help-block">{{ error }}</span>
                      {% endfor %}
                    </div>
                  </div>
                  {% endfor %}
                  <div class="form-group">
                    <div>
                      <button class="btn btn-success" type="submit">Salvar</button>
                    </div>
                  </div>
              </fieldset>
          </form>
      </div>
  </div>
{% endblock %}

templates/funcionarios/especialidade_lista.html
{% extends "index.html" %}

{% block title %}
    Medicos
{% endblock %}

{% block conteudo %}

    <div class="d-flex justify-content-between p-2">
        <h2>Lista de Medicos</h2>
        <a class="btn btn-outline-secondary" href="{% url 'funcionarios:especialidade_cadastro'%}">Cadastrar Especialidade</a></span>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Especialidade</th>
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            {% for especialidade in object_list %}
            <tr>
                <th><a href=""># {{ especialidade.pk }}</a></th>
                <td>{{ especialidade.especialidade }}</td>
                <td>{{ especialidade.descrição }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/funcionarios/funcionario_lista.html
{% extends "index.html" %}

{% block title %}
    Funcionarios
{% endblock %}

{% block conteudo %}
<<div class="d-flex justify-content-between p-2">
    <h2>Lista de Funcionarios</h2>
    <a class="btn btn-outline-secondary" href="{% url 'funcionarios:funcionario_cadastro'%}">Cadastrar Funcionario</a></span>
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Sobrenome</th>
            <th>E-mail</th>
            <th>CPF</th>
            <th>Telefone</th>
            <th>Genero</th>
            <th>CEP</th>
            <th>Data De Nacimento</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for funcionario in object_list %}
        <tr>
            <th><a href=""># {{ funcionario.pk }}</a></th>
            <td>{{ funcionario.user.name }}</td>
            <td>{{ funcionario.user.last_name }}</td>
            <td>{{ funcionario.email }}</td> 
            <td>{{ funcionario.cpf }}</td>
            <td>{{ funcionario.telefone }}</td>
            <td>{{ funcionario.genero }}</td>
            <td>{{ funcionario.cep }}</td>
            <td>{{ funcionario.data_nacimento }}</td>
            <td>{{ funcionario.is_ativo }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/funcionarios/medico_lista.html
{% extends "index.html" %}

{% block title %}
Medicos
{% endblock %}

{% block conteudo %}
<div class="d-flex justify-content-between p-2">
    <h2>Lista de Medicos</h2>
    <a class="btn btn-outline-secondary" href="{% url 'funcionarios:medico_cadastro'%}">Cadastrar Medico</a></span>
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Sobrenome</th>
            <th>CRM</th>
            <th>Especialidade</th>
            {% if user.is_staff or user.is_superuser %}
            <th>ID Funcionario</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for medico in object_list %}
        <tr>
            <th><a href=""># {{ medico.pk }}</a></th>
            <td>{{ medico.funcionario.user.name }}</td>
            <td>{{ medico.funcionario.user.last_name }}</td>
            <td>{{ medico.crm }}</td>
            <td>{{ medico.especialidade }}</td>
            <td>{{ medico.telefone }}</td>
            {% if user.is_staff or user.is_superuser %}
            <td>{{ medico.funcionario }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}