accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [        
    path('minha-conta/', views.index, name='index'),
    path('entrar/', views.login, name='login'),
    path('registrar/', views.singin, name='singup'),
    path('', views.logout , name='logout'),
    
    path('alterar-dados/', views.update_user, name='update_user'),
    path('alterar-senha/', views.update_password, name='update_password'),
    
]

clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('registrar/dados-complementares/', views.cliente_cadastro, name='cliente_cadastro'),
    path('atualizar/', views.cliente_atualizar, name='cliente_atualizar'),
    path('lista/clientes', views.cliente_lista, name='cliente_lista'),
    
    
    path('cadatro/convenio/', views.cliente_atualizar, name='convenio_cadatro'),
    path('cadatro/convenio/plano', views.cliente_atualizar, name='convenio_cadatro'),
    path('lista/convenio', views.convenio_lista, name='convenio_lista'),
    path('lista/convenio/plano', views.plano_lista, name='plano_lista'),
    
    
    path('consultas/criar/', views.consulta_cadastro, name='consulta_cadastro'),
    path('consultas/', views.consulta_lista, name='consulta_lista'),
    
    path('consultas/editar/<int:pk>/', views.consulta_atualizar, name='consulta_update'),
    path('consultas/excluir/<int:pk>/', views.consulta_excluir, name='consulta_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls.conf import include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.index, name='index'),

    path('funcionarios/', include(('funcionarios.urls', 'funcionarios'),namespace='funcionarios')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace= 'clientes')),
    path('contas/', include(('accounts.urls', 'accounts'), namespace= 'accounts')),
]

funcionarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registro/', views.funcionario_cadastro, name='funcionario_cadastro'),
    path('lista/', views.funionarios_lista, name='funcionario_lista'),
    
    path('agendas/', views.agenda_lista, name="agenda_lista"),
    path('agendar/', views.agenda_cadastro, name='agenda_cadastro'),
    path('agendar/atualizar/<int:pk>/', views.agenda_atualizar, name='agendar_consulta_atualizar'),
    path('agendar/apagar/<int:pk>/', views.agenda_deletar, name='agendar_consulta_deletar'),
    
    path('medico/lista/', views.medico_lista, name="medico_lista"),
    path('funcionarios/medico/cadastro', views.medico_cadastro, name='medico_cadastro'),
    path('medico/especialidade/cadastro/', views.especialidade_cadastro, name='especialidade_cadastro'),
    path('medico/especialidade/lista/', views.especialidade_lista, name="especialidade_lista"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="{% static 'css/index/index.css' %}">
  <link rel="stylesheet" href="{% static 'css/index/carrocel.css' %}">
  <link rel="stylesheet" href="{% static 'css/index/sidebar.css' %} ">

  <link rel="stylesheet" href="{% static 'bootstrap-5.3.3-dist/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-5.3.3-dist/css/bootstrap.css.map' %}">
  <link rel="stylesheet" href="{% static '/css/custom.css' %}">

  {% block estilizacao %}{% endblock %}

  <title>{% block titulo %} Dente de Leão {% endblock %}</title>
</head>

<body>
  {% block navbar %}
  <!-- <nav class="navbar navbar-dark fixed-top bg-dark" >
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index'%}">Clinica Dente de Leão</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarDark"
        aria-controls="offcanvasNavbarDark" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbarDark"
        aria-labelledby="offcanvasNavbarDarkLabel">
        <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 100vh; height: 100vh;">
          <button type="button" class="btn-close bg-light" aria-label="Close" data-bs-dismiss="offcanvas">
          </button>
          <a href="" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <svg class="bi pe-none me-2" width="40" height="32">
              <use xlink:href="#bootstrap"></use>
            </svg>
            <span class="fs-4">Dente de Leão</span>
          </a>
          <hr>
          <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
              <a href="#" class="nav-link active" aria-current="page">
                <svg class="bi pe-none me-2" width="16" height="16">
                  <use xlink:href="#home"></use>
                </svg>
                Inicio
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16">
                  <use xlink:href="#speedometer2"></use>
                </svg>
                Minhas Consultas
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16">
                  <use xlink:href="#table"></use>
                </svg>
                Meu Perfil
              </a>
            </li>
          </ul>
          <hr>
          <div class="btn-group dropup">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
              data-bs-toggle="dropdown" aria-expanded="false">
              {% if user.is_authenticated %}
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWvRLMRrytsgoMFgdol3M-vrSgGU-X0vcZKw&s"
                alt="" width="32" height="32" class="rounded-circle me-2">
              <strong>{{ user.username }}</strong>
              {% else %}
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWvRLMRrytsgoMFgdol3M-vrSgGU-X0vcZKw&s"
                alt="" width="32" height="32" class="rounded-circle me-2">
              <strong>Não logado</strong>
              {% endif %}
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
              {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'accounts:index' %}">Minha conta</a></li>
              <li><a class="dropdown-item" href="{% url 'accounts:update_user' %}">Alterar E-mail ou Senha</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sair</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Entrar</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'accounts:singup' %}">Cadastre-se</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown link
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav> -->
  <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index'%}"><img class='navbar-logo' src="{% static 'images/logo_clinica_original.png' %}"> Dente de Leão </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'clientes:consulta_lista'%}">Consultas</a>
          </li>
          {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'funcionarios:agenda_lista'%}">Agendas</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'funcionarios:medico_lista'%}">Medicos</a>
          </li>
          {% endif %}
          {% endif %}
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="#1">Serviços</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#2">Pacientes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#3">Medicos</a>
          </li>
          {% endif %}
        </ul>
        <hr class="border">
        <span>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          {% if user.is_superuser %}
          <li class="nav-item d-flex align-items-center p-2">
            <a class="link-light link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover "
              href="admin/">Administração</a>
          </li>
          {% endif %}
          <li class="nav-item d-flex align-items-center p-2">
            <a class="link-light link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover "
              href="{% url 'accounts:index' %}">Minha Conta</a>
          </li>
          <li class="nav-item p-2">
            <a class="btn btn-outline-danger" href="{% url 'accounts:logout' %}">Sair</a>
          </li>
          {% else %}
            <li class="nav-item d-flex align-items-center p-2">
              <a class="link-light link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover "
                href="{% url 'accounts:login' %}">Entrar</a>
            </li>
            <li class="nav-item p-2">
              <a class="btn btn-outline-success" href="{% url 'accounts:singup' %}">Cadastre-se</a>
            </li>
          {% endif %}
          </ul>
        </span>
      </div>
    </div>
  </nav>
  {% endblock %}
  <div class="container">
    {% block conteudo %}{% endblock %}
  </div>


  {% block footer %}
  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2023–2024 Dente de Leão, LTDA.</p>
  </footer>
  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

templates/delete.html
{% extends "index.html" %}

{% load widget_tweaks %}

{% block title %}
    Apagar | {{ block.super }}
{% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Apagar</h1>
        </div>
        <form action="" method="POST">
            <p>Deseja realmente excluir: <strong>{{ object }}</strong>?</p>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Excluir</button>
            <a href="#" onClick="history.go(-1)" class="btn btn-link"> Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block conteudo %}

{% if user.is_authenticated %}

<!-- <div class="row">
    <div class="col-md-2">
        <div class="list-group">
            <a href="#" class="list-group-item">Minha Conta</a>
            <a href="{% url 'accounts:update_user'%}" class="list-group-item">Alterar Nome e Email</a>
            <a href="{% url 'accounts:update_password'%}" class="list-group-item">Alterar Senha</a>
            <a href="{% url 'clientes:cliente_atualizar'%}" class="list-group-item">Minhas Informaçoes</a>
            <a href="{% url 'clientes:consulta_lista'%}" class="list-group-item">Consultas</a>
            {% if request.user.is_staff or request.user.is_superuser %}
            <a href="{% url 'funcionarios:agenda_lista'%}" class="list-group-item">Agendas</a>
            <a href="{% url 'funcionarios:funcionario_lista'%}" class="list-group-item">Funcionarios</a>
            <a href="{% url 'funcionarios:medico_lista'%}" class="list-group-item">Medicos</a>
            <a href="{% url 'funcionarios:especialidade_lista'%}" class="list-group-item">Especialidade</a>
            <a href="" class="list-group-item">Convenios <span class="badge bg-warning">Manutenção</span></a>
            <a href="" class="list-group-item">Planos <span class="badge bg-warning">Manutenção</span></a>
            <a href="" class="list-group-item">Serviços <span class="badge bg-warning">Manutenção</span></a>
            <a href="{% url 'clientes:cliente_lista'%}" class="list-group-item">Clientes <span class="badge bg-warning">Manutenção</span></a>
            <a href="" class="list-group-item">Usuarios <span class="badge bg-warning">Manutenção</span></a>
            {% endif %}
        </div>
    </div>
</div> -->

<div class="row">
    <h1>Bem-Vindo, {{ user }}</h1>
</div>
{% else %}
<div id="nao-logado">
    <main>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="index-img" src="https://images.adsttc.com/media/images/627a/75f3/7f4d/9601/651d/aa7e/medium_jpg/154-hr-11a-dentist-amsterdam-waitingroom-reception-rooms-i29.jpg?1652192764" alt="">
                <div class="container">
                    <div class="carousel-caption text-start bg-success bg-opacity-50 p-2 rounded">
                        <h1>Bem-Vindo a Clinica Odontologica Dente de Leão.</h1>
                        <p class="opacity-75">Faça seu cadastro para poder usufruir dos nossos serviços.</p>
                        <p><a class="btn btn-lg btn-success" href="{% url 'accounts:singup' %}">Cadastre-se!</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>


        <div class="container marketing">
            <div class="row" id="1">
                <div class="col-lg-4">
                    <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                        src="https://cdn-icons-png.flaticon.com/512/1957/1957362.png" role="img"
                        aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="var(--bs-secondary-color)" />
                    <h2 class="fw-normal">Clínico Geral</h2>
                    <p>São realizados os tratamentos mais simples, como consultas preventivas, limpezas, remoção de
                        tártaro, entre outros procedimentos.</p>
                </div>
                <div class="col-lg-4">
                    <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                        src="https://png.pngtree.com/png-vector/20191016/ourlarge/pngtree-dentist-stomatology-tooth-implant-vector-icon-png-image_1804158.jpg"
                        role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="var(--bs-secondary-color)" />
                    <h2 class="fw-normal">Implantodontia</h2>
                    <p>Os implantes são utilizados nos casos em que os outros dentes não estão comprometidos, auxiliando
                        na recuperação da mastigação e fala, além de melhorar a estética, trazendo uma maior autoestima
                        ao paciente.</p>
                </div>
                <div class="col-lg-4">
                    <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                        src="https://static.vecteezy.com/ti/vetor-gratis/p3/20271283-dental-ponte-linha-icone-ortodontico-dentes-implantar-linear-pictograma-oral-cuidado-estomatologia-protese-odontologia-esboco-simbolo-dental-tratamento-placa-editavel-avc-isolado-ilustracao-vetor.jpg"
                        role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="var(--bs-secondary-color)" />
                    <h2 class="fw-normal">Prótese Dentária</h2>
                    <p>Reconstrução e reposição dos dentes danificados ou perdidos. O uso de próteses influencia
                        positivamente a mastigação, dicção e estética do paciente</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtELX64j5LG3-FcJ7bOf4jj2rg-6IuipWj0g&s"
                        role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="var(--bs-secondary-color)" />
                    <h2 class="fw-normal">Dentística</h2>
                    <p>Área responsável por proporcionar um sorriso mais harmonioso, com dentes brancos e alinhados. A
                        tecnologia por trás dos procedimentos estéticos já possibilita que esse tipo de tratamento seja
                        acessível a todos.</p>
                </div>
                <div class="col-lg-4">
                    <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                        src="https://www.clinicadentalaltea.com/images/ico/odontopediatria.svg" role="img"
                        aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="var(--bs-secondary-color)" />
                    <h2 class="fw-normal">Odontopediatria</h2>
                    <p>Mesmo durante a dentição de leite, elas já estão suscetíveis a cáries e outros problemas, por
                        isso é preciso visitar um profissional.</p>
                </div>
                <div class="col-lg-4">
                    <img class="bd-placeholder-img rounded-circle" width="140" height="140"
                        src="https://static.vecteezy.com/ti/vetor-gratis/p1/20487099-suspensorios-dentes-linha-icone-ortodontia-bracadeira-dente-cuidado-e-medico-mandibula-correcao-linear-pictograma-odontologia-esboco-simbolo-dental-tratamento-placa-editavel-avc-isolado-ilustracao-vetor.jpg"
                        role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="var(--bs-secondary-color)" />
                    <h2 class="fw-normal">Ortodontia</h2>
                    <p>Por meio do uso de aparelhos dentários, os pacientes de todas as idades podem corrigir o
                        posicionamento dos dentes e ossos faciais, tornando o sorriso mais harmônico e funcional.</p>
                </div>
            </div>

            <hr class="featurette-divider">

            <div class="row featurette" id="2">
                <div class="col-md-7">
                    <h2 class="featurette-heading fw-normal lh-1">Informação do paciente. </h2>
                    <p class="lead">Saiba como se preparar para uma consulta conosco e o que você pode esperar durante a
                        consulta e o tratamento. Verifique nossas perguntas frequentes para obter mais informações e
                        aprender sobre os planos de pagamento flexíveis que oferecemos.
                    </p>
                </div>
                <div class="col-md-5">
                    <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500"
                        height="500"
                        src="https://rodrigoalmada.com.br/wp-content/uploads/2020/06/dentista-de-confianca.jpg"
                        aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="var(--bs-secondary-bg)" />
                </div>
            </div>

            <hr class="featurette-divider">

            <div class="row featurette" id="3">
                <div class="col-md-7 order-md-2">
                    <h2 class="featurette-heading fw-normal lh-1">Para médicos solicitantes. </h2>
                    <p class="lead">Agradecemos a confiança demonstrada pelos GPs quando nos permitem cuidar de seus
                        pacientes. Orgulhamo-nos de nos comunicar com o médico e profissional de saúde que nos indicou
                        antes e depois de atendermos o paciente.</p>
                </div>
                <div class="col-md-5 order-md-1">
                    <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500"
                        height="500"
                        src="https://www.codental.com.br/blog/wp-content/uploads/2021/05/agenda-de-dentista.jpg"
                        aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="var(--bs-secondary-bg)" />
                </div>
            </div>

            <hr class="featurette-divider">

            <div class="row featurette">
                <div class="col-md-7">
                    <h2 class="featurette-heading fw-normal lh-1">Precisa de opções de pagamento?</h2>
                    <p class="lead">Oferecemos planos de pagamento flexíveis para quaisquer procedimentos cirúrgicos na
                        Clínica Dente de Leão. Isso significa menos tempo se preocupando e mais tempo para se concentrar
                        no que é realmente importante – você.</p>
                </div>
            </div>

            <hr class="featurette-divider">
        </div>
    </main>
</div>
</div>
{% endif %}

{% endblock %}