clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('registrar/dados-complementares/', views.cliente_cadastro, name='cliente_cadastro'),
    path('atualizar/', views.cliente_atualizar, name='cliente_atualizar'),
    path('lista/clientes', views.cliente_lista, name='cliente_lista'),
    
    
    path('cadatro/convenio/', views.cliente_atualizar, name='convenio_cadatro'),
    path('cadatro/convenio/plano', views.cliente_atualizar, name='convenio_cadatro'),
    path('lista/convenio', views.convenio_lista, name='convenio_lista'),
    path('lista/convenio/plano', views.plano_lista, name='plano_lista'),
    
    
    path('consultas/criar/', views.consulta_cadastro, name='consulta_cadastro'),
    path('consultas/', views.consulta_lista, name='consulta_lista'),
    
    path('consultas/editar/<int:pk>/', views.consulta_atualizar, name='consulta_update'),
    path('consultas/excluir/<int:pk>/', views.consulta_excluir, name='consulta_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls.conf import include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.index, name='index'),

    path('funcionarios/', include(('funcionarios.urls', 'funcionarios'),namespace='funcionarios')),
    path('clientes/', include(('clientes.urls', 'clientes'), namespace= 'clientes')),
    path('contas/', include(('accounts.urls', 'accounts'), namespace= 'accounts')),
]

clientes/models.py
from django.db import models
from django.conf import settings
from django.core.validators import RegexValidator
from django_cpf_cnpj.fields import CPFField, CNPJField
from django.db.models.fields.related import ManyToManyField, OneToOneField, ForeignKey
from funcionarios.models import *
from accounts.models import *

class Convenio(models.Model):
    convenio = models.CharField('Convenio', max_length=200)
    cnpj = CNPJField(masked=True)
    
    def __str__(self):
        return f'{self.convenio}'

class ServicoCoberto(models.Model):
    servico = models.CharField('Serviços', max_length=200)
    descricao = models.CharField('Descrição', max_length=1000)
    
    def __str__(self):
        return f'{self.servico}'

class PlanoConvenio(models.Model):
    plano = models.CharField('Plano', max_length=30)
    convenio = ForeignKey(Convenio, on_delete=models.CASCADE, related_name='plano_convenio')
    
    def __str__(self):
        return f'{self.plano}-{self.convenio}'

class ServicoPlano(models.Model):
    servico = ManyToManyField(ServicoCoberto, related_name='serviço_plano')
    plano = ManyToManyField(PlanoConvenio, related_name='servico_plano')
    
    def __str__(self):
        return f'{self.servico}-{self.plano}'

class Cliente(models.Model):
    
    nome = models.CharField(verbose_name='Nome', max_length=30)
    sobrenome = models.CharField(verbose_name='Sobremone', max_length=200)

    cpf = CPFField(verbose_name="CPF", max_length=50, unique=True,)
    
    GENERO = (
        ("MAS", "Masculino"),
        ("FEM", "Feminino"),
        ("OTR", "Outro"),
    )
    
    genero = models.CharField(verbose_name="Genero", max_length=9, choices=GENERO)
    
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="O número precisa estar neste formato: \
                        '+99 99 9999-0000'."
    )
    telefone = models.CharField(verbose_name="Telefone", validators=[phone_regex],max_length=17, null=True, blank=True)
    
    
    convenio = ForeignKey(Convenio, on_delete=models.CASCADE, related_name='clientes')
    plano = ForeignKey(PlanoConvenio, on_delete=models.CASCADE, related_name='clientes')
    
    cep = models.CharField('CEP', max_length=9)
    rua = models.CharField('Rua', max_length=200)
    numero = models.CharField('Numero', max_length=15)
    complemento = models.CharField('Complemento', max_length=200, blank=True, null=True)
    municipio = models.CharField('Municipio', max_length=20)
    unidade_federal = models.CharField('Unidade Federal', max_length=2)
    
    data_nacimento = models.DateField('Data de Nacimento')
    data_inicio = models.DateField('Data de Inicio', auto_now_add=True)
    
    is_ativo = models.BooleanField('Está ativo', default=True)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, 
        verbose_name='Usuário',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.nome}'
    
class Consulta(models.Model):
    agenda =  OneToOneField(Agenda, on_delete=models.CASCADE, related_name='consulta')
    cliente = ForeignKey(Cliente, on_delete=models.CASCADE, related_name='consulta')
    
    class Meta:
        unique_together = ('agenda', 'cliente')
        
    def __str__(self):
        return f'{self.agenda} - {self.cliente}'

clientes/forms.py
from django import forms
from . import models

class ClienteForm(forms.Form):
    class Meta:
        model = models.Cliente
        fields = ['cpf', 'genero', 'telefone', 'convenio', 'plano', 'cep', 'rua', 'numero', 'complemento', 'municipio', 'unidade_federal', 'data_nacimento']
        # fields = '__all__'
class ConvenioForm(forms.Form):
    class Meta:
        model = models.Convenio
        fields = ['convenio', 'cnpj']

class PlanoForm(forms.Form):
    class Meta:
        model = models.Convenio
        fields = ['plano', 'convenio']

clientes/views.py
from django.db import IntegrityError
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from .models import *
from .forms import *


class TestMixinIsAdmin(UserPassesTestMixin):
    def test_func(self):
        is_admin_or_is_staff = self.request.user.is_superuser or \
            self.request.user.is_staff
        return bool(is_admin_or_is_staff)

    def handle_no_permission(self):
        messages.error(
            self.request, "Você não tem permissões!"
        )
        return redirect("accounts:index")

class ClienteCreateView(LoginRequiredMixin ,CreateView):
    
    model = Cliente
    template_name = 'clientes/cadastro.html'
    form_class = ClienteForm
    success_url = reverse_lazy('index')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    
    def get_endereco(self):
        pass
    
class ClienteUpdateView(LoginRequiredMixin, UpdateView):

    model = Cliente
    login_url = reverse_lazy('accounts:login')
    template_name = 'accounts/update_user.html'
    fields = ['cpf', 'genero', 'telefone', 'convenio', 'plano', 'cep', 'rua', 'numero', 'complemento', 'municipio', 'unidade_federal', 'data_nacimento']


    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        user = self.request.user
        try:
            return Cliente.objects.get(user=user)
        except Cliente.DoesNotExist:
            return None
        
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class ClienteListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    model = Cliente
    login_url = 'accounts:login'
    template_name = 'clientes/cliente_lista.html'

    def get_queryset(self):
        return self.model.objects.all().order_by('-pk')
    
class ConvenioCreateView(LoginRequiredMixin ,CreateView):
    
    model = Convenio
    template_name = 'clientes/cadastro.html'
    form_class = ConvenioForm
    success_url = reverse_lazy('index')
    # success_url = reverse_lazy('clientes:cadastro_plano')

    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
        
class PlanoCreateView(LoginRequiredMixin ,CreateView):
    
    model = PlanoConvenio
    template_name = 'clientes/cadastro.html'
    form_class = PlanoForm
    success_url = reverse_lazy('index')
    # success_url = reverse_lazy('clientes:cadastro_planos')

    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class ConveioListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'clientes/convenio_lista.html'

    def get_queryset(self):
        return Convenio.objects.all().order_by('-pk')
    
class PlanosListView(LoginRequiredMixin, TestMixinIsAdmin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'medicos/lista.html'
    
    def get_queryset(self, request):
        return Convenio.objects.filter(request).order_by('-pk')

class ConsultaCreateView(LoginRequiredMixin, CreateView):

    model = Consulta
    login_url = 'accounts:login'
    template_name = 'clientes/cadastro.html'
    fields = ['agenda']
    success_url = reverse_lazy('clientes:consulta_list')
    
    def form_valid(self, form):
        try:
            form.instance.cliente = Cliente.objects.get(user=self.request.user)
            form.save()
        except IntegrityError as e:
            if 'UNIQUE constraint failed' in e.args[0]:
                messages.warning(self.request, 'Você não pode marcar esta consulta')
                return HttpResponseRedirect(reverse_lazy('clientes:consulta_create'))
        except Cliente.DoesNotExist:
            messages.warning(self.request, 'Complete seu cadastro')
            return HttpResponseRedirect(reverse_lazy('clientes:cliente_cadastro'))
        messages.info(self.request, 'Consulta marcada com sucesso!')
        return HttpResponseRedirect(reverse_lazy('clientes:consulta_list'))
    
class ConsultaUpdateView(LoginRequiredMixin, UpdateView):

    model = Consulta
    login_url = 'accounts:login'
    template_name = 'clientes/cadastro.html'
    fields = ['agenda']
    success_url = reverse_lazy('clientes:consulta_lista')
    
    def form_valid(self, form):
        form.instance.cliente = Cliente.objects.get(user=self.request.user)
        return super().form_valid(form)
    
class ConsultaDeleteView(LoginRequiredMixin, DeleteView):
    model = Consulta
    success_url = reverse_lazy('clientes:consulta_list')
    template_name = 'form_delete.html'

    def get_success_url(self):
        messages.success(self.request, "Consulta excluída com sucesso!")
        return reverse_lazy('clientes:consulta_list')


class ConsultaListView(LoginRequiredMixin, ListView):
    
    login_url = 'accounts:login'
    template_name = 'clientes/consulta_lista.html'

    def get_queryset(self):
        user=self.request.user
        try:
            cliente = Cliente.objects.get(user=user)
        except Cliente.DoesNotExist:
            messages.warning(self.request, 'Crie uma Consulta')
            return None
        try:
            consultas = Consulta.objects.filter(cliente=cliente).order_by('-pk')
        except Consulta.DoesNotExist:
            messages.warning(self.request, 'Crie uma Consulta')
            return None
        return consultas


cliente_cadastro = ClienteCreateView.as_view()
cliente_atualizar = ClienteUpdateView.as_view()
cliente_lista = ClienteListView.as_view()

convenio_cadatrar = ConvenioCreateView.as_view()
convenio_lista = ConveioListView.as_view()
plano_lista = PlanosListView.as_view()

consulta_cadastro = ConsultaCreateView.as_view()
consulta_lista = ConsultaListView.as_view()
consulta_atualizar = ConsultaUpdateView.as_view()
consulta_excluir = ConsultaDeleteView.as_view()

templates/clientes/cadastro.html
{% extends "index.html" %}

{% load widget_tweaks %}

{% block title %}
    Cadastro | {{ block.super }}
{% endblock %}

{% block conteudo %}
<div class="row">
    <div>
        <div class="page-header">
            <h1>Cadastro</h1>
        </div>
        <div>
          <a href="{% url 'clientes:consulta_lista' %}">Voltar</a>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">
                  {{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
                <div class="form-group">
                  <div>
                    <button class="btn btn-success" type="submit">Salvar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

templates/clientes/cliente_lista.html
{%extends 'base.html'%}

{% load widget_tweaks %}

{% block title %}
Lista de Clientes
{% endblock %}

{% block conteudo %}
<h2>lista dos Clientes </h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>CPF</th>
      <th>E-mail</th>
      <th>Telefone</th>
    </tr>
  </thead>
  <tbody>
    {% for cliente in object_list %}
    <tr>
      <th><a href=""># {{ cliente.pk }}</a></td>
      <td>{{ cliente.nome }}</td>
      <td>{{ cliente.sobrenome }}</td>
      <td>{{ cliente.cpf }}</td>
      <td>{{ cliente.user.email }}</td>
      <td>{{ cliente.telefone }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

templates/clientes/consulta_cadastro.html
{% extends "index.html" %}

{% load widget_tweaks %}

{% block title %}
Cadastro Consulta | {{ block.super }}
{% endblock %}

{% block conteudo %}
<div class="row">
  <div>
    <div class="page-header">
      <h1>Consulta</h1>
    </div>
    <div>
      <a href="{% url 'clientes:consulta_lista' %}">Voltar</a>
    </div>
    <form class="form-horizontal" method="post">
      {% csrf_token %}
      {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error }}
      </div>
      {% endfor %}
      <fieldset>
        {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.auto_id }}" class="col-md-3 control-label">
            {{ field.label }}</label>
          <div class="col-md-9">
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
        {% endfor %}
        <div class="form-group">
          <div>
            <button class="btn btn-success" type="submit">Salvar</button>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}

templates/clientes/consulta_lista.html
{%extends 'base.html'%}

{% load widget_tweaks %}

{% block title %}
Consultas
{% endblock %}

{% block conteudo %}
<div class="d-flex justify-content-between p-2">
    <h2>Lista de Consultas</h2>
    <a class="btn btn-outline-secondary" href="{% url 'clientes:consulta_cadastro'%}">Cadastrar Nova Consulta</a></span>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Medico</th>
      <th>Dia</th>
      <th>Horario</th>
      {% if user.is_staff or user.is_superuser %}
      <th>Paciente</th>
      {% endif %}
      <th>Opções</th>
    </tr>
  </thead>
  <tbody>
    {% for consulta in object_list %}
    <tr>
      <th><a href=""># {{ cliente.pk }}</a></td>
      <td>{{ consulta.agenda.medico }}</td>
      <td>{{ consulta.agenda.dia|date:"d/m/Y" }}</td>
      <td>{{ consulta.agenda.get_horario_display }}</td>
      {% if user.is_staff or user.is_superuser %}
      <td>{{ consulta.cliente }}</td>
      {% endif %}
      <td>
        <a href="{% url 'clientes:consulta_update'%}" class="text-primary" style="padding-left: 10px; text-decoration: none;">
            <i class="fas fa-edit"></i>
        </a>
        <a href="{% url 'clientes:consulta_delete'%}" class="mr-1 text-danger" style="padding-left: 10px; text-decoration: none;">
            <i class="fas fa-trash-alt"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}